export { default as promos} from './promos'
export { default as location } from './location'
export { default as menuList } from './menuList'
export { default as milkList } from './milkList'
export { default as availableRewards } from './availableRewards'